### test index

GET http://localhost:8080/../answer/01-rcli/deny.toml HTTP/1.1

### Test static file with tower-http

GET http://localhost:8080/Cargo.toml HTTP/1.1

### Test static directory with tower-http

GET http://localhost:8080/src HTTP/1.1
